/** Types */
export const DO_LOGIN = 'DO_LOGIN';
export const UPDATE_AUTH_STATE = 'UPDATE_AUTH_STATE';
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT';
export const ADD_MESSAGE_TO_LIST = 'ADD_MESSAGE_TO_LIST';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const ADD_USER_ONLINE_TO_LIST = 'ADD_USER_ONLINE_TO_LIST';
export const SET_MENU_TOP_INFO = 'SET_MENU_TOP_INFO';

